databases:
  - name: ubiquity
    databaseName: ubiquity
    user: ubiquity
    plan: free

services:
  - type: web
    name: ubiquity
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ubiquity
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default


  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: redis://red-cse6odu8ii6s738tohf0:6379
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: e5a8741ad1f08ae3451a0cc71c41ef2f
        sync: false
  - type: web
    name: rails-web
    runtime: ruby
    region: ohio
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: redis://red-cse6odu8ii6s738tohf0:6379
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: e5a8741ad1f08ae3451a0cc71c41ef2f
        sync: false
